// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdWrjMAHSi8MwPJEqRoUAeo4FzfNMUaTI',
    appId: '1:762510779199:web:129332c16dc0728c3e298a',
    messagingSenderId: '762510779199',
    projectId: 'icab-private-app-8a740',
    authDomain: 'icab-private-app-8a740.firebaseapp.com',
    storageBucket: 'icab-private-app-8a740.firebasestorage.app',
    measurementId: 'G-69SFNZP73Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3RdLC-zp1AkhNyMh1P_dw5xaJAWnIP9k',
    appId: '1:762510779199:android:6f79c0925c69a5de3e298a',
    messagingSenderId: '762510779199',
    projectId: 'icab-private-app-8a740',
    storageBucket: 'icab-private-app-8a740.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYf5fE523hzbAvuCVdMAAhDyRfoDsePk0',
    appId: '1:762510779199:ios:5c1ac4771d13e6fa3e298a',
    messagingSenderId: '762510779199',
    projectId: 'icab-private-app-8a740',
    storageBucket: 'icab-private-app-8a740.firebasestorage.app',
    androidClientId: '762510779199-md1cb408pa033dhd1pc38fm23h6h81rk.apps.googleusercontent.com',
    iosClientId: '762510779199-87fdidbbi1rrsvusrejohkch15ejpd4j.apps.googleusercontent.com',
    iosBundleId: 'com.AshrafIT.elearningapp.eLearningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYf5fE523hzbAvuCVdMAAhDyRfoDsePk0',
    appId: '1:762510779199:ios:5c1ac4771d13e6fa3e298a',
    messagingSenderId: '762510779199',
    projectId: 'icab-private-app-8a740',
    storageBucket: 'icab-private-app-8a740.firebasestorage.app',
    androidClientId: '762510779199-md1cb408pa033dhd1pc38fm23h6h81rk.apps.googleusercontent.com',
    iosClientId: '762510779199-87fdidbbi1rrsvusrejohkch15ejpd4j.apps.googleusercontent.com',
    iosBundleId: 'com.AshrafIT.elearningapp.eLearningApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgNfHmoUgC0sNbP3QivW-mdaAVRBPNekA',
    appId: '1:762510779199:web:119ad8c708284ca63e298a',
    messagingSenderId: '762510779199',
    projectId: 'icab-private-app-8a740',
    authDomain: 'icab-private-app-8a740.firebaseapp.com',
    storageBucket: 'icab-private-app-8a740.firebasestorage.app',
    measurementId: 'G-7Y570XYPN6',
  );
}
